### ISSUE TITLE
Unable to find component cover.myq

### ISSUE THREAD

**Issue by plainslice** [arraylabs/myq#6]
Not sure what is going on. 

I just did a fresh isntall and copied over my old yaml files, so nothing has changed. 

Now, Im getting this error: 

```
17-02-10 18:49:27 homeassistant.loader: Unable to find component cover.myq
17-02-10 18:49:27 homeassistant.bootstrap: Unable to find platform cover.myq
```

This is my config:

```
cover:
  - platform: myq
    username: !secret cover_username
    password: !secret cover_password
    brand: liftmaster
```
